grafana/nethax

Makefile
The `.gitignore` expects that the probe binary is located in the bin directory
=> fix: Probe binary should be output into bin

go.mod, pkg/kubernetes/kubernetes_test.go
https://tip.golang.org/doc/go1.24#testingpkgtesting
Go 1.24 introduces T.Context() which can be used in tests instead of context.TODO().
This PR makes use of those. It also updates the go.mod version to 1.24.
Can be tested with `make test`.
=> fix: Use go 1.24 Testing Contexts in tests

cmd/runner/executetest.go, pkg/kubernetes/kubernetes.go, pkg/kubernetes/kubernetes_test.go
The Kubernetes package was built during a hackathon and was done quickly.
This refactors the package to:
- Attach methods to the Kubernetes object rather than use static methods (avoid duplicate calls to GetKubernetes)
- Allow Kubeconfig to be overridden, load from default kubeconfig path without hard coding
- Accept a context if given (currently not configurable by flag; will do in a follow up PR to refactor flags)
You can test this by:
```Console
k --context kind-kind create ns otel-demo
k --context kind-kind create cm -n otel-demo grafana-dashboards
k --context kind-kind replace --namespace otel-demo -f https://raw.githubusercontent.com/open-telemetry/opentelemetry-demo/main/kubernetes/opentelemetry-demo.yaml
make clean test build docker
[...]
./bin/runner execute-test -f …
```
=> fix: Refactor kubernetes package

example/OtelDemoTestPlan.yaml
I forgot to fix this; I was testing to ensure that the tests would fail properly, but I think the example should have all passing tests.
=> fix: Example test plan had a typo in it

CONTRIBUTING.md, Dockerfile-probe, Dockerfile-runner, Makefile
Adds:
- `CONTRIBUTING.md` file with getting started instructions
- Make target to initialize a test cluster with kind
- Make target to run the example test plan against test cluster
- Various fixes to Makefile syntax
- Use same syntax in both Dockerfiles
You can test this locally by running make kind-init-oteldemo run-example-test-plan.
=> fix: Improve Contributor Experience

cmd/probe/http_probe.go, cmd/probe/http_probe_test.go, cmd/probe/main.go, cmd/probe/probe.go, cmd/probe/tcp_probe.go, cmd/probe/tcp_probe_test.go
Refactor `cmd/probe` probes to reduce duplication of logic and also to make them more testeables.
The main different in `main.go` is that the amount of information display is reduced, however we gain better maintainability.
=> Refactor probes to reduce duplication

.github/workflows/docker.yml, Makefile
Now that we're using this for more than simple test cases locally, this needs to live somewhere more permanent.
This change pushes tags and main branch builds to Docker Hub. This can form the start of our releasing process. I will cut a v0.0.1 tag after this is merged.
=> chore: Push to Docker Hub

.github/workflows/docker.yml, Dockerfile-probe, Dockerfile-runner, Makefile
We were getting a build error with the previous version, which was pointing at the `-X` flag of `go build -ldflags` not being properly formatted. By only passing the version instead of the whole import path for overriding the value at compile time we hope it will fix this error.
#10 9.570 /usr/local/go/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value
=> Pass PROBE_VERSION as version instead of full -X flag

cmd/runner/testplan.go, go.mod, go.sum
The previous package is now archived and not maintained anymore. The replacement package is even recommended by the author of gopkg.in/yaml [1]. See also this [proposal] for the Prometheus project where they discussed the same replacement.
[1]: https://www.reddit.com/r/golang/comments/1gi33h1/is_there_a_path_forward_for_gos_yaml_situation/
[proposal]: https://github.com/prometheus/proposals/issues/49
=> Replace gopkg.in/yaml.v2 with goccy/go-yaml

cmd/runner/executetest.go, cmd/runner/executetest_test.go
This PR adds some unit tests for `cmd/runner`, and by doing so refactors the `findPods` a little bit to make it more testable. These are definitely not a full test suite for pod selection logic, but should cover most of the cases.
=> Add unit tests for selecting pods

cmd/runner/executetest.go, pkg/kubernetes/kubernetes.go, pkg/kubernetes/kubernetes_test.go
This PR refactos `pkg/kubernetes` to make it a bit more Goish™, and also tries add some missing unit tests. I think the full _files_ view should be enough, but in any case each commit is trying to be as small and scoped as possible so it might be easier to review that way.
=> Refactor `pkg/kubernetes`

renovate.json
Renovate is opening PRs that don't pass our tidiness check. This should fix it.
Relevant docs:
https://docs.renovatebot.com/configuration-options/\#postupdateoptions
https://docs.renovatebot.com/golang/\#module-tidying
Configures Renovate to run a `go mod tidy` after updating.
I ran `make test kind-init-otel-demo run-example-test-plan` and everything worked fine :+1:
=> fix: Renovate should tidy up after itself

.github/workflows/docker.yml, Makefile
This improves the docker build + release process:
- We should be able to release tags now
- Docker builds will only happen when there are changes to files or permissions
- tags a `latest` image whenever a build is run
- local builds will now use a version number based on the latest commit + any uncommitted changes
- this avoids docker rebuilding in cases when the code hasn't changed :)
- uses the Docker Hub login action
- only run Docker build + push on tags starting with v
- adds docker-push to Makefile
- renames Makefile target docker to docker-build for clarity
- calls make docker-build docker-push in GH action after docker is logged in
I ran `act` on the GH actions and they parsed + ran properly.
For the docker build side, I rebuilt the containers a few times with and without local …
=> Push Tags to Docker Hub

cmd/probe/tcp_probe_test.go
We were missing testing the case when the TCP probe can't dial to an address and we were expecting it to actually fail.
Add fixing test case in `cmd/probe/tcp_probe_test.go`.
Close the listener before attempting to run a probe that expects the connection to fail.
N/A
=> Fix TCP probe success test

cmd/probe/main.go, cmd/runner/executetest.go, pkg/probeflags/probeflags.go, pkg/probeflags/probeflags_test.go
The probe flags are defined in `cmd/probe` and then used in `cmd/runner` -- this coupling is implicit and error prone.
This refactor pulls the probe flag strings out into a common package and defines a function to turn the strings into parseable flags. You can execute tests for this with `make test`.
=> fix: Refactor probe flags

Makefile
The previous attempt to push docker images used a push command that didn't conform to the docs:
https://docs.docker.com/reference/cli/docker/image/push/
- fix: Properly push the tagged images to the registry
- fix: Whitespace
Ran `make docker-build docker-push` locally and got permission issues pushing to Docker Hub -- will test further once this is merged to `main`.
Since this is a change to CI, I may need to iterate on this change with a few follow up PRs -- but since we've never pushed an image to Docker Hub it should be safe. Once this is done, I'll document the release process for nethax.
=> fix: Docker Hub pushes should use a proper push command

CONTRIBUTING.md, renovate.json
Renovate should use automerge so that PRs are merged by Renovate once checks are passing and the PR has been approved. This change will cause Renovate to enable automerge on PRs it creates.
- Enables automerge in Renovate config
N/A (will test next time Renovate runs)
Relevant docs: https://docs.renovatebot.com/configuration-options/#automerge
=> fix: Enable Renovate automerge

README.md, cmd/runner/executetest.go, cmd/runner/testplan.go, cmd/runner/testplan_test.go
Previously when we were printing the selector in the test execution,
it was looking something like the following:
Selector: {all k8s-app=kube-dns }
Namespace: kube-system
Selection Mode: all
This is using the default format Go uses for structs, which is not
very human readable, and could be confusing of both labels and fields
are used. With this new method, the above message would look like:
Selector: mode: all, labels: k8s-app=kube-dns
Namespace: kube-system
Additionally, if fields were also used, it would look like:
Selector: mode: all, labels: k8s-app=kube-dns, fields: spec.nodeName=foo-bar-42
Namespace: kube-system
Implement [`fmt.Stringer`](https://pkg.go.dev/fmt#Stringer) interface for `PodSelector`.
Add tests for different `PodSelector` values and compare against the expected …
=> fix: Add `PodSelector.String` method

Makefile
The previous PR didn't include `grafana` in the `docker push`, so it was trying to push to the Docker Hub library. The registry should include the `grafana` org.
- Include `grafana` in the registry path
N/A - need to test with a GHA run
=> fix: Push images to Grafana's repos

Makefile
I found myself doing this manually to ensure I wasn't reducing overall test coverage with my changes!
Just adds test coverage to the output of `make test` :)
`make test` works
This PR is itty bitty!
=> fix: Adds test coverage output to Make target

Dockerfile-probe, Dockerfile-runner, Makefile, cmd/runner/executetest.go, cmd/runner/testdata/example.yml, cmd/runner/testplan.go, cmd/runner/testplan_test.go, example/OtelDemoTestPlan.yaml, pkg/kubernetes/kubernetes.go, pkg/kubernetes/kubernetes_test.go
Adds the ability to configure probe images, making it possible to run images in Kubernetes regardless of probe image registry.
- add probe image as parameter to launch ephemeral container
- add probe image as flag on the runner
- add per-test probe image config
- simplifies ephemeral container tests -- the code was doing extra setup/teardown that isn't required with our mock
- set the default image to use Docker Hub
- ensure kind loads the fully qualified image name into the control plane
- updates the example YAML and `--help` output messages
- Unit tests added
- `make test kind-init-oteldemo run-example-test-plan` works correctly
- Implemented as discussed
- Tried to make small commits to make review easier! <3
=> Adds Configurability for Probe Images

cmd/runner/executetest.go
Add `--context/-c` to `cmd/runner` so we can connect directly from a local machine to a Kubernetes cluster in `~/.kube/config`, or in-cluster if left empty.
Add `--context` flag.
Tried locally against a live cluster.
N/A
=> feat: Add `--context` flag to override the Kubernetes cluster

cmd/runner/testplan.go
While migrating some old test plans I've found that I mistyped a key (`selector` instead of `podSelector`) in the configuration file and the parsing silently succeeded yet the execution failed because some fields weren't properly valued. By passing the strict decoding option parsing will fail if it encounters a field name that isn't recognized, enabling faster and better feedback to users.
Use [`yaml.Strict`](https://pkg.go.dev/github.com/goccy/go-yaml#Strict) decoding option.
Manually changed the YAML file to change the casing and name of some fields.
N/A
=> Enable strict YAML parsing

Dockerfile-probe, Dockerfile-runner, Makefile
With the growing presence of Arm workloads in cloud environments, it's important to be able to run probes anywhere. This change adds buildx config and adds support to the dockerfile to build for various target platforms.
For now, we'll target the same platforms as alloy (https://github.com/grafana/alloy/blob/aadcc9ff59345cb00cb5c35c09e4f249c5c73a06/tools/ci/docker-containers\#L72).
- Adds [support to Dockerfiles for buildx platform variables](https://docs.docker.com/build/building/multi-platform/#cross-compiling-a-go-application)
- Modifies Makefile to use buildx and pass in platforms (list of platforms taken from alloy)
I ran `make docker-build` locally and it looked good 🚀 
You may need to enable the containerd image store if you haven't already: …
=> feat: Add multi-platform support for docker builds via buildx

cmd/nethax-probe/dns_probe.go, cmd/nethax-probe/dns_probe_test.go, cmd/nethax-probe/main.go, cmd/nethax/testplan.go, cmd/nethax/testplan_test.go, example/OtelDemoTestPlan.yaml, pkg/probeflags/probeflags.go
This PR adds a new DNS kind probe that allows checking if resolving a domain name works.
* Add `DNSProbe` type.
* Add `-type=dns` flag option.
Added test suite.
Note that there's a hack to test the context aware requisite of a probe, probably related with [this issue](https://github.com/golang/go/issues/71939).
=> [nethax-probe]: Add DNS probe
